name: k2e
description: K2 Survey App

dependencies:
  flutter:
    sdk: flutter

  sqflite: 0.8.2
  http: ^0.11.3
  path_provider: ^0.3.1
  json_annotation: ^0.2.3
  redux: ^3.0.0
  flutter_redux: ^0.5.0
  scoped_model: ^0.2.0
  uuid: 1.0.0
  validator: ">=0.0.4 <0.1.0"
  camera: ^0.2.1
  video_player: ^0.6.4
  image_picker: ^0.4.6

  google_sign_in: ^3.0.5
  firebase_auth: ^0.5.19
  firebase_storage: ^1.0.2
  cloud_firestore: ^0.7.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: 0.16.7

dev_dependencies:
  build_runner:
  json_serializable: ^0.5.4
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#  plugin:
#    androidPackage: io.flutter.plugins.camera
#    pluginClass: CameraPlugin

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"