name: k2e
description: K2 Survey App

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^0.11.2+2
  http: ^0.11.3+17
#  connectivity: ^0.4.0
  path_provider: ^0.4.1
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  scoped_model: ^0.3.0
  camera: ^0.2.3
  geolocator: '^2.1.1'
  video_player: ^0.6.5
  image_picker: ^0.4.10
  cached_network_image: ^0.4.2
  flutter_cache_manager: ^0.1.2
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

  google_sign_in: ^3.0.5
  firebase_auth: ^0.5.20
  shared_preferences: ^0.4.2
  firebase_storage: 1.0.2
  image: ^2.0.4
  cloud_firestore: ^0.8.0
  dropdown_menu: ^1.1.0
  intl: ^0.15.7
  xml: ^3.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.18.1

dev_dependencies:
  build_runner:
#  json_serializable: ^0.5.4
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#  plugin:
#    androidPackage: io.flutter.plugins.camera
#    pluginClass: CameraPlugin

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
